Iter5
tamazyanarsen/http-short-url- pull request #5
Opened 2024-04-21 03:57 UTC by tamazyanarsen

2024-04-23 22:18 UTC, avhitrov requested changes
1. Гонки при работе с хранилищем.
2. Рекомендация по разделению хендлеров.
3. Хранилище желательно тоже вынести в отдельный пакет и передавать в хендлеры из раутера; но лучше сделать структуру `app`, к которой привязать объект хранилища, и хендлеры отпочковать от `app`.

2024-04-23 22:18 UTC, avhitrov commented on cmd/shortener/handler.go
> +var urls = make(map[string]string)
Мапы - структуры потоконебезопасные и в конкурентной среде (а http-сервер априори является конкурентным приложением, так как на каждый запрос пользователя хендлер открывается в отдельной горутине) должны защищаться блокировкой. Можно использовать либо sync.Mutex (sync.RWMutex), либо потокобезопасную мапу sync.Map.

https://t.me/bushigo/24

В данной версии кода получаем:
```
==================
WARNING: DATA RACE
Write at 0x00c000088c30 by goroutine 7:
  runtime.mapassign_faststr()
      C:/Apps/Go/src/runtime/map_faststr.go:203 +0x0
  main.MainHandler()
      D:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler.go:30 +0x8a4
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:436 +0x488
  github.com/go-chi/chi.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:87 +0x681
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous read at 0x00c000088c30 by goroutine 23:
  main.MainHandler()
      D:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler.go:18 +0x116
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:436 +0x488
  github.com/go-chi/chi.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:87 +0x681
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x556
  main.main()
      D:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/main.go:16 +0x407

Goroutine 23 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x556
  main.main()
      D:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/main.go:16 +0x407
==================
save ==================
aHR0cHM6WARNING: DATA RACE to map; result:
Read at 0x00c00011a508 by https://asiatimes.com/goroutine 25:

  main.MainHandler()
      D:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler.go:18 +0x166
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:436 +0x488
  github.com/go-chi/chi.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:87 +0x681
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Previous write at 0x00c00011a508 by goroutine 7:
  main.MainHandler()
      D:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler.go:30 +0x8b3
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).routeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:436 +0x488
  github.com/go-chi/chi.(*Mux).routeHTTP-fm()
      <autogenerated>:1 +0x51
  net/http.HandlerFunc.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:2166 +0x47
  github.com/go-chi/chi.(*Mux).ServeHTTP()
      C:/Users/ahitrov/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:87 +0x681
  net/http.serverHandler.ServeHTTP()
      C:/Apps/Go/src/net/http/server.go:3137 +0x2a1
  net/http.(*conn).serve()
      C:/Apps/Go/src/net/http/server.go:2039 +0x13c4
  net/http.(*Server).Serve.gowrap3()
      C:/Apps/Go/src/net/http/server.go:3285 +0x4f

Goroutine 25 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x556
  main.main()
      D:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/main.go:16 +0x407

Goroutine 7 (running) created at:
  net/http.(*Server).Serve()
      C:/Apps/Go/src/net/http/server.go:3285 +0x8ec
  net/http.(*Server).ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3184 +0xbc
  net/http.ListenAndServe()
      C:/Apps/Go/src/net/http/server.go:3438 +0x556
  main.main()
      D:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/main.go:16 +0x407
==================
```

2024-04-23 22:18 UTC, avhitrov commented on cmd/shortener/main.go
> +	r.Post("/", MainHandler)
Лучше все-таки разделить хендлеры и использовать отдельные функции для каждого эндпоинта, общие действия, вроде проверки пользователя или gzip, помещать в мидлваре. В дальнейшем количество обрабатываемых сервером эндпоинтов заметно вырастет, и будет очень сложно поддерживать одну функцию на все действия.

2024-04-23 22:18 UTC, avhitrov commented on cmd/shortener/main.go
> +		return
```suggestion
		log.Fatal(err)
```
так принято.

2024-05-02 21:14 UTC, avhitrov approved these changes
Пока ok. Дальше сторадж все-таки придется усложнять и приводить к концепции интерфейсов.

2024-05-03 08:21 UTC, tamazyanarsen commented
> Пока ok. Дальше сторадж все-таки придется усложнять и приводить к концепции интерфейсов.

понял, спасибо

сделаю рефакторинг в следующем спринте

2024-05-03 08:22 UTC, merged