Iter9
tamazyanarsen/http-short-url- pull request #9
Opened 2024-06-16 05:33 UTC by tamazyanarsen

2024-06-20 10:19 UTC, avhitrov requested changes
Необходимо отрефакторить код.
1. Избавиться от init, всю последовательность инициализации сервера контролировать в main()
2. Обрабатывать ошибки. Не использовать Fatal нигде, кроме main(), все возникающие ошибки поднимать вверх и обрабатывать максимально высоко.
3. Уменьшить цикломатическую сложность кода.

2024-06-20 10:19 UTC, avhitrov commented on cmd/shortener/handler/handler.go
> +}
Вообще не факт, что данная функция init() будет выполнена после выполнения init(), осуществляющей чтение конфигурации. Файл в этом случае не сможет быть прочитан. Более того, никак не отрабатывается и не проверяется ошибка.

Вообще использование init не очень приветствуется именно по причине возможного (и нередкого) возникновения коллизий между вызываемыми init разных пакетов. Рассчитывать в одном пакете, что к моменту запуска отработает init из другого пакета - верх безрассудства.

В общем, есть функция main(), в ней следует задавать последовательность всех действий по инициализации. И в случае возникновения ошибок следует падать по log.Fatal (строго внутри main), не доводя до запуска сервера с нерабочими модулями.

2024-06-22 05:30 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +				}
вот тут не понял

как я это могу вынести в middleware, если такой заголовок нужно проставлять только для случаев, когда ответ в формате json

в middleware я еще не знаю тип ответа, поэтому не могу там заранее проставить такой заголовок

я попробовал, автотесты, конечно же, упали

2024-06-22 05:31 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +	}
исправлено

2024-06-22 05:31 UTC, tamazyanarsen commented on cmd/shortener/main.go
>  	r := chi.NewRouter()
исправлено

2024-06-22 05:31 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +		sugarLogger.Fatalln(err)
исправлено

2024-06-22 05:32 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +					sugarLogger.Fatalln(err)
исправлено

2024-06-22 05:32 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +}
исправлено

2024-06-26 22:48 UTC, avhitrov commented on cmd/shortener/handler/handler.go
> +				}
Вообще его можно выставлять для любого Content-Type. По сути, он зависит только от пользовательского Accept-Encoding. Ну и его можно завязать на пользовательский же Content-Type, если хочется. Везде, где пользователь отправляет данные в формате JSON, в ответ он также получает данные в формате JSON.

2024-06-26 23:22 UTC, avhitrov requested changes
Предыдущие ошибки исправлены, стало возможно тестировать и ревьюить дальше. Вот список замечаний:
1. Нарушен приоритет опроса аргументов командной строки и переменных окружения
2. При установке имени файла в заранее неверное значение сервер запускается, несмотря на ошибку открытия файла, и на все запросы сыпет ошибками в логи
3. При установке имени файла в пустое значение `-f=""` должен происходить откат на in-memory модель стораджа. Этого не происходит.
4. Прочие замечания в комментариях к коду.

2024-06-26 23:22 UTC, avhitrov commented on cmd/shortener/handler/handler.go
> +func writeToFile(shortURL string, body []byte) bool {
```suggestion
func writeToFile(shortURL string, body []byte) error {
```
Если в процессе работы функции родилась ошибка, ее и надо возвращать. То, что результат записи в файл в виде `true` - это не записанный файл, вообще не очевидно.

2024-06-26 23:22 UTC, avhitrov commented on cmd/shortener/main.go
>  	flag.Parse()
Вот эта функция должна находиться между описанием флагов и обработкой переменных окружения. В текущей конфигурации она нарушает приоритет, описанный в ТЗ, так как сначала отработают функции работы с окружением, а потом flag.Parse закроет их значение аргументами командной строки.

2024-06-26 23:22 UTC, avhitrov commented on cmd/shortener/handler/handler.go
> +func InitHandler() {
```suggestion
func InitHandler() error {
```

2024-06-26 23:22 UTC, avhitrov commented on cmd/shortener/handler/handler.go
> +		return
```suggestion
		return err
```

2024-06-26 23:22 UTC, avhitrov commented on cmd/shortener/main.go
> +	handler.InitHandler()
```suggestion
	if err := handler.InitHandler(); err != nil {
		log.Fatal(err)
	}
```
Иначе получаем при неверном названии файла на любой запрос:
```
2024-06-27T01:56:44.390+0300    ERROR   handler/handler.go:170  open G:\aaa: The system cannot find the path specified.
http-short-url/cmd/shortener/handler.writeToFile
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler/handler.go:170
http-short-url/cmd/shortener/handler.PostURL
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler/handler.go:161
net/http.HandlerFunc.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:2166
github.com/go-chi/chi.(*Mux).routeHTTP
        C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:436
net/http.HandlerFunc.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:2166
http-short-url/cmd/shortener/handler.WithLog.func1
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler/handler.go:77
net/http.HandlerFunc.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:2166
http-short-url/cmd/shortener/handler.GzipHandler.func1
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler/handler.go:128
net/http.HandlerFunc.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:2166
github.com/go-chi/chi.(*Mux).ServeHTTP
        C:/Users/Khitrov_An/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:87
net/http.serverHandler.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:3137
net/http.(*conn).serve
        C:/Apps/Go/src/net/http/server.go:2039
2024-06-27T01:56:44.390+0300    INFO    handler/handler.go:78   duration: 1.4976ms
2024-06-27T01:56:44.391+0300    INFO    handler/handler.go:79
----------------------------------------------------------
```

2024-06-26 23:22 UTC, avhitrov commented on cmd/shortener/handler/handler.go
> +	}
Если в процессе записи возникла ошибка, то сервер все равно выставит статус `StatusCreated`, что неверно. Аналогично в других хендлерах.

2024-09-22 05:10 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +		handleError(respErr, w)
исправлено

2024-09-22 05:11 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +func writeToFile(shortURL string, body []byte) bool {
исправлено

2024-09-22 05:26 UTC, tamazyanarsen commented on cmd/shortener/main.go
>  	flag.Parse()
проверил, работает корректно

добавлю пару логов, чтобы показать работу

там же происходит перезапись самого ключа `Config["a"]`

приоритет не нарушен

2024-09-22 05:29 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +func InitHandler() {
исправлено

2024-09-22 05:29 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +		return
исправлено

2024-09-22 05:31 UTC, tamazyanarsen commented on cmd/shortener/main.go
> +	handler.InitHandler()
исправлено

2024-09-26 03:42 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +	}
исправлено

2024-09-26 22:35 UTC, avhitrov requested changes
Указанные замечания, в основном, исправлены, но осталось одно, для реализации которого придется зарефакторить код. 
При указании пустого значения в качестве имени файла система должна откатываться на работу с in-memory хранилищем. В текущей реализации при указании `-f=""` сервер просто падает на старте.
Как это правильно решить:
1. Для начала все подпапки из `cmd/shortener` стоит перенести в `internal` и ссылаться уже туда
2. Создать для файлового хранилища и in-memory хранилища единый интерфейс с реализацией функций Put, Get (и GetAll, например) и поместить его куда-нибудь в `internal/storage`. Реализацию этого интерфейса для памяти и для файла в виде подпапок сложить внутрь `internal/storage`, кроме того, для каждого хранилища сделать свою функцию инициализации, возвращающую объект данного хранилища (структуру, реализующую функции Get и Put и имеющую поля, необходимые для конкретной реализации).
3. После инициализации конфига создать код, который будет решать, какое хранилище создавать, и инициализировать конкретное хранилище.
4. Инициализированное хранилище передавать в хендлеры в виде интерфейса, а в хендлерах дергать уже функции Get или Put.

В дальнейших итерациях появится третье хранилище и требование поддержания обратной совместимости по всем новым внедряемым функциям. Если не отрефакторить на данном этапе, в дальнейшем код станет запутанным до неподдерживаемости.

2024-09-26 22:35 UTC, avhitrov commented on cmd/shortener/handler/handler.go
> +	if writeToFile(shortURL, []byte(body.URL)) != nil {
Перед return еще надо бы выставить статус. Для данного случая подойдет 500.

2024-09-29 04:30 UTC, tamazyanarsen commented
> 2\. Создать для файлового хранилища и in-memory хранилища единый интерфейс

готово

интерфейс был, но я ошибся и начал работать напрямую с хранилищем файла, поторопился

провел рефакторинг кода, вернул общение через общий интерфейс (data.Store)

2024-11-23 23:42 UTC, avhitrov requested changes
Осталась одно замечание по обработке ошибки в момент инициализации стораджа. В остальном на данном этапе все приемлемо. При подходе к следующему блоку изменений предлагаю обсудить более аккуратную реализацию сервера на 1-1.

2024-11-23 23:42 UTC, avhitrov commented on cmd/shortener/handler/handler.go
> +		fileStore.InitMapStore()
Функция возвращает ошибку, причем на разных этапах своего исполнения. Ошибку необходимо ловить и обрабатывать. В противном случае получим неработающий сторадж, который будет отламываться при любом запросе
```
2024-11-24T02:17:34.361+0300    ERROR   data/store.go:60        open z:\aaaa: The system cannot find the path specified.
http-short-url/cmd/shortener/data.(*FileStore).Write
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/data/store.go:60
http-short-url/cmd/shortener/handler.shortName
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler/handler.go:190
http-short-url/cmd/shortener/handler.PostURL
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler/handler.go:164
net/http.HandlerFunc.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:2166
github.com/go-chi/chi.(*Mux).routeHTTP
        C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:436
net/http.HandlerFunc.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:2166
http-short-url/cmd/shortener/handler.WithLog.func1
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler/handler.go:84
net/http.HandlerFunc.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:2166
http-short-url/cmd/shortener/handler.GzipHandler.func1
        C:/work/src/github.com/tamazyanarsen/http-short-url-/cmd/shortener/handler/handler.go:135
net/http.HandlerFunc.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:2166
github.com/go-chi/chi.(*Mux).ServeHTTP
        C:/Users/ahitr/go/pkg/mod/github.com/go-chi/chi@v1.5.5/mux.go:87
net/http.serverHandler.ServeHTTP
        C:/Apps/Go/src/net/http/server.go:3137
net/http.(*conn).serve
        C:/Apps/Go/src/net/http/server.go:2039
```

Правильный паттерн - не смогли при старте инициализировать сторадж, надо падать. Наверх возвращается ошибка и на самом верху дергается `log.Fatal` (или явно `os.Exit(1)`)

2024-11-26 09:50 UTC, tamazyanarsen commented on cmd/shortener/handler/handler.go
> +		fileStore.InitMapStore()
исправил

закинул встречу по календарю на завтра на 10.30

2024-12-06 04:38 UTC, merged